# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bartek/Programming/kr260_bare_metal_example/kr260_bare_metal_example.srcs/sources_1/bd/add_bram/ip/add_bram_axi_bram_ctrl_0_bram_0/add_bram_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'add_bram_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bartek/Programming/kr260_bare_metal_example/kr260_bare_metal_example.gen/sources_1/bd/add_bram/ip/add_bram_axi_bram_ctrl_0_bram_0/add_bram_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_bram_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/bartek/Programming/kr260_bare_metal_example/kr260_bare_metal_example.srcs/sources_1/bd/add_bram/ip/add_bram_axi_bram_ctrl_0_bram_0/add_bram_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'add_bram_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bartek/Programming/kr260_bare_metal_example/kr260_bare_metal_example.gen/sources_1/bd/add_bram/ip/add_bram_axi_bram_ctrl_0_bram_0/add_bram_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_bram_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
