# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/add_bram/add_bram.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==add_bram || ORIG_REF_NAME==add_bram} -quiet] -quiet

# IP: bd/add_bram/ip/add_bram_zynq_ultra_ps_e_0_0/add_bram_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==add_bram_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==add_bram_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/add_bram/ip/add_bram_axi_bram_ctrl_0_0/add_bram_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==add_bram_axi_bram_ctrl_0_0 || ORIG_REF_NAME==add_bram_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/add_bram/ip/add_bram_axi_smc_0/add_bram_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==add_bram_axi_smc_0 || ORIG_REF_NAME==add_bram_axi_smc_0} -quiet] -quiet

# IP: bd/add_bram/ip/add_bram_rst_ps8_0_99M_0/add_bram_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==add_bram_rst_ps8_0_99M_0 || ORIG_REF_NAME==add_bram_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/add_bram/ip/add_bram_axi_bram_ctrl_0_bram_0/add_bram_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==add_bram_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==add_bram_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# XDC: /home/bartek/Programming/kr260_bare_metal_example/kr260_bare_metal_example.gen/sources_1/bd/add_bram/add_bram_ooc.xdc
